name = 'Mazoku Legends'

modules = [
    './chat',
    './main',
    './mobile-gui',
    './default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = 'intro'
    graphic = 'hero2'
    hitbox = [16, 16]

[compilerOptions.build]
    serverUrl = 'https://mazokulegendsserver.onrender.com'